#[cfg(test)]
mod tests {
    use crate::*;
    use pretty_assertions::assert_eq;

    #[test]
    fn reset() {
        let notroot = serde_json::to_string(&Reset::NotRoot).unwrap();
        assert_eq!("0", notroot);
        assert_eq!(Reset::NotRoot, serde_json::from_str(&notroot).unwrap());

        let no = serde_json::to_string(&Reset::No).unwrap();
        assert_eq!("1", no);
        assert_eq!(Reset::No, serde_json::from_str(&no).unwrap());

        let yes = serde_json::to_string(&Reset::Yes(vec![])).unwrap();
        assert_eq!("[]", yes);
        assert_eq!(Reset::Yes(vec![]), serde_json::from_str(&yes).unwrap());

        let yes = serde_json::to_string(&Reset::Yes(vec![123, 456, 789])).unwrap();
        assert_eq!("[123,456,789]", yes);
        assert_eq!(
            Reset::Yes(vec![123, 456, 789]),
            serde_json::from_str(&yes).unwrap()
        );
    }

    #[test]
    fn order() {
        let mut todos = Profile::new(
            "test".to_string(),
            vec![
                Task {
                    name: String::from("test1"),
                    description: None,
                    due: None,
                    tags: vec![],
                    subtasks: vec![
                        Task {
                            name: String::from("test1"),
                            description: None,
                            due: Some(Due {
                                start: 2,
                                end: None,
                                only_date: false,
                                repeat: None,
                                repeat_step: None,
                            }),
                            tags: vec![],
                            subtasks: vec![],
                            reset_on_done: Reset::NotRoot,
                            priority: 0,
                            done: Done::Undone,
                            overdue: false,
                            index: 0,
                        },
                        Task {
                            name: String::from("test2"),
                            description: None,
                            due: None,
                            tags: vec![],
                            subtasks: vec![],
                            reset_on_done: Reset::NotRoot,
                            priority: 0,
                            done: Done::Done,
                            overdue: true,
                            index: 0,
                        },
                        Task {
                            name: String::from("test3"),
                            description: None,
                            due: Some(Due {
                                start: 1,
                                end: None,
                                only_date: false,
                                repeat: None,
                                repeat_step: None,
                            }),
                            tags: vec![],
                            subtasks: vec![],
                            reset_on_done: Reset::NotRoot,
                            priority: 1000,
                            done: Done::Done,
                            overdue: true,
                            index: 0,
                        },
                        Task {
                            name: String::from("test4"),
                            description: None,
                            due: None,
                            tags: vec![],
                            subtasks: vec![],
                            reset_on_done: Reset::NotRoot,
                            priority: 100,
                            done: Done::Undone,
                            overdue: true,
                            index: 0,
                        },
                    ],
                    reset_on_done: Reset::No,
                    priority: 0,
                    done: Done::Undone,
                    overdue: true,
                    index: 0,
                },
                Task {
                    name: String::from("test2"),
                    description: None,
                    due: None,
                    tags: vec![],
                    subtasks: vec![],
                    reset_on_done: Reset::No,
                    priority: 0,
                    done: Done::Done,
                    overdue: true,
                    index: 0,
                },
                Task {
                    name: String::from("test3"),
                    description: None,
                    due: None,
                    tags: vec![],
                    subtasks: vec![],
                    reset_on_done: Reset::No,
                    priority: 1000,
                    done: Done::Done,
                    overdue: false,
                    index: 0,
                },
                Task {
                    name: String::from("test4"),
                    description: None,
                    due: None,
                    tags: vec![],
                    subtasks: vec![],
                    reset_on_done: Reset::No,
                    priority: 100,
                    done: Done::Undone,
                    overdue: false,
                    index: 0,
                },
            ],
            vec![],
        );
        let correct = Profile::new(
            "test".to_string(),
            vec![
                Task {
                    name: String::from("test4"),
                    description: None,
                    due: None,
                    tags: vec![],
                    subtasks: vec![],
                    reset_on_done: Reset::No,
                    priority: 100,
                    done: Done::Undone,
                    overdue: false,
                    index: 1,
                },
                Task {
                    name: String::from("test1"),
                    description: None,
                    due: None,
                    tags: vec![],
                    subtasks: vec![
                        Task {
                            name: String::from("test1"),
                            description: None,
                            due: Some(Due {
                                start: 2,
                                end: None,
                                only_date: false,
                                repeat: None,
                                repeat_step: None,
                            }),
                            tags: vec![],
                            subtasks: vec![],
                            reset_on_done: Reset::NotRoot,
                            priority: 0,
                            done: Done::Undone,
                            overdue: true,
                            index: 3,
                        },
                        Task {
                            name: String::from("test2"),
                            description: None,
                            due: None,
                            tags: vec![],
                            subtasks: vec![],
                            reset_on_done: Reset::NotRoot,
                            priority: 0,
                            done: Done::Done,
                            overdue: false,
                            index: 4,
                        },
                        Task {
                            name: String::from("test3"),
                            description: None,
                            due: Some(Due {
                                start: 1,
                                end: None,
                                only_date: false,
                                repeat: None,
                                repeat_step: None,
                            }),
                            tags: vec![],
                            subtasks: vec![],
                            reset_on_done: Reset::NotRoot,
                            priority: 1000,
                            done: Done::Done,
                            overdue: true,
                            index: 5,
                        },
                        Task {
                            name: String::from("test4"),
                            description: None,
                            due: None,
                            tags: vec![],
                            subtasks: vec![],
                            reset_on_done: Reset::NotRoot,
                            priority: 100,
                            done: Done::Undone,
                            overdue: false,
                            index: 6,
                        },
                    ],
                    reset_on_done: Reset::No,
                    priority: 0,
                    done: Done::Undone,
                    overdue: false,
                    index: 2,
                },
                Task {
                    name: String::from("test3"),
                    description: None,
                    due: None,
                    tags: vec![],
                    subtasks: vec![],
                    reset_on_done: Reset::No,
                    priority: 1000,
                    done: Done::Done,
                    overdue: false,
                    index: 7,
                },
                Task {
                    name: String::from("test2"),
                    description: None,
                    due: None,
                    tags: vec![],
                    subtasks: vec![],
                    reset_on_done: Reset::No,
                    priority: 0,
                    done: Done::Done,
                    overdue: false,
                    index: 8,
                },
            ],
            vec![],
        );

        todos.order();

        assert_eq!(todos, correct);
    }

    #[test]
    fn filter() {
        let profile = Profile::new(
            "p1".to_string(),
            vec![
                Task {
                    name: String::from("test1"),
                    description: None,
                    due: None,
                    tags: vec!["hi".to_string(), "hello".to_string()],
                    subtasks: vec![Task {
                        name: String::from("test1_1"),
                        description: None,
                        due: None,
                        tags: vec!["hi".to_string(), "hello".to_string()],
                        subtasks: vec![],
                        reset_on_done: Reset::No,
                        priority: 0,
                        done: Done::Undone,
                        overdue: false,
                        index: 2,
                    }],
                    reset_on_done: Reset::No,
                    priority: 0,
                    done: Done::Undone,
                    overdue: false,
                    index: 1,
                },
                Task {
                    name: String::from("test2"),
                    description: None,
                    due: None,
                    tags: vec![],
                    subtasks: vec![],
                    reset_on_done: Reset::No,
                    priority: 0,
                    done: Done::Undone,
                    overdue: false,
                    index: 3,
                },
                Task {
                    name: String::from("test3"),
                    description: None,
                    due: None,
                    tags: vec![],
                    subtasks: vec![],
                    reset_on_done: Reset::No,
                    priority: 0,
                    done: Done::Undone,
                    overdue: false,
                    index: 4,
                },
                Task {
                    name: String::from("test4"),
                    description: None,
                    due: None,
                    tags: vec!["hi".to_string(), "hello".to_string()],
                    subtasks: vec![],
                    reset_on_done: Reset::No,
                    priority: 0,
                    done: Done::Undone,
                    overdue: false,
                    index: 5,
                },
            ],
            vec![],
        );
        assert_eq!(
            vec![
                profile.nth_task(1).unwrap(),
                profile.nth_task(2).unwrap(),
                profile.nth_task(5).unwrap()
            ],
            profile.filter(|todo| todo.tags == vec!["hi".to_string(), "hello".to_string()])
        )
    }

    #[test]
    fn nth_todo() {
        let todos = Profile::new(
            "test".to_string(),
            vec![
                Task {
                    name: String::from("test1"),
                    description: None,
                    due: None,
                    tags: vec![],
                    subtasks: vec![
                        Task {
                            name: String::from("test1"),
                            description: None,
                            due: None,
                            tags: vec![],
                            subtasks: vec![],
                            reset_on_done: Reset::NotRoot,
                            priority: 0,
                            done: Done::Undone,
                            overdue: true,
                            index: 2,
                        },
                        Task {
                            name: String::from("test2"),
                            description: None,
                            due: None,
                            tags: vec![],
                            subtasks: vec![],
                            reset_on_done: Reset::NotRoot,
                            priority: 0,
                            done: Done::Done,
                            overdue: true,
                            index: 3,
                        },
                        Task {
                            name: String::from("test3"),
                            description: None,
                            due: None,
                            tags: vec![],
                            subtasks: vec![],
                            reset_on_done: Reset::NotRoot,
                            priority: 1000,
                            done: Done::Done,
                            overdue: false,
                            index: 4,
                        },
                        Task {
                            name: String::from("test4"),
                            description: None,
                            due: None,
                            tags: vec![],
                            subtasks: vec![],
                            reset_on_done: Reset::NotRoot,
                            priority: 100,
                            done: Done::SubUndone,
                            overdue: false,
                            index: 5,
                        },
                    ],
                    reset_on_done: Reset::No,
                    priority: 0,
                    done: Done::Undone,
                    overdue: true,
                    index: 1,
                },
                Task {
                    name: String::from("test2"),
                    description: None,
                    due: None,
                    tags: vec![],
                    subtasks: vec![],
                    reset_on_done: Reset::No,
                    priority: 0,
                    done: Done::Done,
                    overdue: true,
                    index: 6,
                },
                Task {
                    name: String::from("test3"),
                    description: None,
                    due: None,
                    tags: vec![],
                    subtasks: vec![],
                    reset_on_done: Reset::No,
                    priority: 1000,
                    done: Done::Done,
                    overdue: false,
                    index: 7,
                },
                Task {
                    name: String::from("test4"),
                    description: None,
                    due: None,
                    tags: vec![],
                    subtasks: vec![],
                    reset_on_done: Reset::No,
                    priority: 100,
                    done: Done::SubUndone,
                    overdue: false,
                    index: 8,
                },
            ],
            vec![],
        );
        let todo = todos.nth_task(7).unwrap();
        assert_eq!(
            todo,
            &Task {
                name: String::from("test3"),
                description: None,
                due: None,
                tags: vec![],
                subtasks: vec![],
                reset_on_done: Reset::No,
                priority: 1000,
                done: Done::Done,
                overdue: false,
                index: 7,
            }
        );

        let todo = todos.nth_task(3).unwrap();
        assert_eq!(
            todo,
            &Task {
                name: String::from("test2"),
                description: None,
                due: None,
                tags: vec![],
                subtasks: vec![],
                reset_on_done: Reset::NotRoot,
                priority: 0,
                done: Done::Done,
                overdue: true,
                index: 3,
            }
        );
    }

    #[test]
    fn nth_todo_mut() {
        let mut todos = Profile::new(
            "test".to_string(),
            vec![
                Task {
                    name: String::from("test1"),
                    description: None,
                    due: None,
                    tags: vec![],
                    subtasks: vec![
                        Task {
                            name: String::from("test1"),
                            description: None,
                            due: None,
                            tags: vec![],
                            subtasks: vec![],
                            reset_on_done: Reset::NotRoot,
                            priority: 0,
                            done: Done::Undone,
                            overdue: true,
                            index: 2,
                        },
                        Task {
                            name: String::from("test2"),
                            description: None,
                            due: None,
                            tags: vec![],
                            subtasks: vec![],
                            reset_on_done: Reset::NotRoot,
                            priority: 0,
                            done: Done::Done,
                            overdue: true,
                            index: 3,
                        },
                        Task {
                            name: String::from("test3"),
                            description: None,
                            due: None,
                            tags: vec![],
                            subtasks: vec![],
                            reset_on_done: Reset::NotRoot,
                            priority: 1000,
                            done: Done::Done,
                            overdue: false,
                            index: 4,
                        },
                        Task {
                            name: String::from("test4"),
                            description: None,
                            due: None,
                            tags: vec![],
                            subtasks: vec![],
                            reset_on_done: Reset::NotRoot,
                            priority: 100,
                            done: Done::SubUndone,
                            overdue: false,
                            index: 5,
                        },
                    ],
                    reset_on_done: Reset::No,
                    priority: 0,
                    done: Done::Undone,
                    overdue: true,
                    index: 1,
                },
                Task {
                    name: String::from("test2"),
                    description: None,
                    due: None,
                    tags: vec![],
                    subtasks: vec![],
                    reset_on_done: Reset::No,
                    priority: 0,
                    done: Done::Done,
                    overdue: true,
                    index: 6,
                },
                Task {
                    name: String::from("test3"),
                    description: None,
                    due: None,
                    tags: vec![],
                    subtasks: vec![],
                    reset_on_done: Reset::No,
                    priority: 1000,
                    done: Done::Done,
                    overdue: false,
                    index: 7,
                },
                Task {
                    name: String::from("test4"),
                    description: None,
                    due: None,
                    tags: vec![],
                    subtasks: vec![],
                    reset_on_done: Reset::No,
                    priority: 100,
                    done: Done::SubUndone,
                    overdue: false,
                    index: 8,
                },
            ],
            vec![],
        );

        let todo = todos.nth_task_mut(7).unwrap();
        assert_eq!(
            todo,
            &mut Task {
                name: String::from("test3"),
                description: None,
                due: None,
                tags: vec![],
                subtasks: vec![],
                reset_on_done: Reset::No,
                priority: 1000,
                done: Done::Done,
                overdue: false,
                index: 7,
            }
        );

        let todo = todos.nth_task_mut(3).unwrap();
        assert_eq!(
            todo,
            &mut Task {
                name: String::from("test2"),
                description: None,
                due: None,
                tags: vec![],
                subtasks: vec![],
                reset_on_done: Reset::NotRoot,
                priority: 0,
                done: Done::Done,
                overdue: true,
                index: 3,
            }
        );
    }

    #[test]
    fn root_nth_todo_idx() {
        let todos = Profile::new(
            "test".to_string(),
            vec![
                Task {
                    name: String::from("test1"),
                    description: None,
                    due: None,
                    tags: vec![],
                    subtasks: vec![
                        Task {
                            name: String::from("test1"),
                            description: None,
                            due: None,
                            tags: vec![],
                            subtasks: vec![Task {
                                name: String::from("test1_1"),
                                description: None,
                                due: None,
                                tags: vec![],
                                subtasks: vec![],
                                reset_on_done: Reset::NotRoot,
                                priority: 0,
                                done: Done::Undone,
                                overdue: true,
                                index: 2,
                            }],
                            reset_on_done: Reset::NotRoot,
                            priority: 0,
                            done: Done::Undone,
                            overdue: true,
                            index: 3,
                        },
                        Task {
                            name: String::from("test2"),
                            description: None,
                            due: None,
                            tags: vec![],
                            subtasks: vec![],
                            reset_on_done: Reset::NotRoot,
                            priority: 0,
                            done: Done::Done,
                            overdue: true,
                            index: 4,
                        },
                        Task {
                            name: String::from("test3"),
                            description: None,
                            due: None,
                            tags: vec![],
                            subtasks: vec![],
                            reset_on_done: Reset::NotRoot,
                            priority: 1000,
                            done: Done::Done,
                            overdue: false,
                            index: 5,
                        },
                        Task {
                            name: String::from("test4"),
                            description: None,
                            due: None,
                            tags: vec![],
                            subtasks: vec![],
                            reset_on_done: Reset::NotRoot,
                            priority: 100,
                            done: Done::SubUndone,
                            overdue: false,
                            index: 6,
                        },
                    ],
                    reset_on_done: Reset::No,
                    priority: 0,
                    done: Done::Undone,
                    overdue: true,
                    index: 1,
                },
                Task {
                    name: String::from("test2"),
                    description: None,
                    due: None,
                    tags: vec![],
                    subtasks: vec![],
                    reset_on_done: Reset::No,
                    priority: 0,
                    done: Done::Done,
                    overdue: true,
                    index: 7,
                },
                Task {
                    name: String::from("test3"),
                    description: None,
                    due: None,
                    tags: vec![],
                    subtasks: vec![],
                    reset_on_done: Reset::No,
                    priority: 1000,
                    done: Done::Done,
                    overdue: false,
                    index: 8,
                },
                Task {
                    name: String::from("test4"),
                    description: None,
                    due: None,
                    tags: vec![],
                    subtasks: vec![],
                    reset_on_done: Reset::No,
                    priority: 100,
                    done: Done::SubUndone,
                    overdue: false,
                    index: 9,
                },
            ],
            vec![],
        );
        let correct = 3;

        let todo = todos.root_nth_task_idx(2).unwrap();
        assert_eq!(todo, correct);
    }

    #[test]
    fn remove_nth_todo() {
        let mut todos = Profile::new(
            "test".to_string(),
            vec![
                Task {
                    name: String::from("test1"),
                    description: None,
                    due: None,
                    tags: vec![],
                    subtasks: vec![
                        Task {
                            name: String::from("test1_1"),
                            description: None,
                            due: None,
                            tags: vec![],
                            subtasks: vec![],
                            reset_on_done: Reset::NotRoot,
                            priority: 0,
                            done: Done::Undone,
                            overdue: true,
                            index: 2,
                        },
                        Task {
                            name: String::from("test2"),
                            description: None,
                            due: None,
                            tags: vec![],
                            subtasks: vec![],
                            reset_on_done: Reset::NotRoot,
                            priority: 0,
                            done: Done::Done,
                            overdue: true,
                            index: 3,
                        },
                        Task {
                            name: String::from("test3"),
                            description: None,
                            due: None,
                            tags: vec![],
                            subtasks: vec![],
                            reset_on_done: Reset::NotRoot,
                            priority: 1000,
                            done: Done::Done,
                            overdue: false,
                            index: 4,
                        },
                        Task {
                            name: String::from("test4"),
                            description: None,
                            due: None,
                            tags: vec![],
                            subtasks: vec![],
                            reset_on_done: Reset::NotRoot,
                            priority: 100,
                            done: Done::SubUndone,
                            overdue: false,
                            index: 5,
                        },
                    ],
                    reset_on_done: Reset::No,
                    priority: 0,
                    done: Done::Undone,
                    overdue: true,
                    index: 1,
                },
                Task {
                    name: String::from("test2"),
                    description: None,
                    due: None,
                    tags: vec![],
                    subtasks: vec![],
                    reset_on_done: Reset::No,
                    priority: 0,
                    done: Done::Done,
                    overdue: true,
                    index: 6,
                },
                Task {
                    name: String::from("test3"),
                    description: None,
                    due: None,
                    tags: vec![],
                    subtasks: vec![],
                    reset_on_done: Reset::No,
                    priority: 100,
                    done: Done::SubUndone,
                    overdue: false,
                    index: 7,
                },
            ],
            vec![],
        );
        let correct = Profile::new(
            "test".to_string(),
            vec![
                Task {
                    name: String::from("test1"),
                    description: None,
                    due: None,
                    tags: vec![],
                    subtasks: vec![
                        Task {
                            name: String::from("test2"),
                            description: None,
                            due: None,
                            tags: vec![],
                            subtasks: vec![],
                            reset_on_done: Reset::NotRoot,
                            priority: 0,
                            done: Done::Done,
                            overdue: true,
                            index: 3,
                        },
                        Task {
                            name: String::from("test3"),
                            description: None,
                            due: None,
                            tags: vec![],
                            subtasks: vec![],
                            reset_on_done: Reset::NotRoot,
                            priority: 1000,
                            done: Done::Done,
                            overdue: false,
                            index: 4,
                        },
                        Task {
                            name: String::from("test4"),
                            description: None,
                            due: None,
                            tags: vec![],
                            subtasks: vec![],
                            reset_on_done: Reset::NotRoot,
                            priority: 100,
                            done: Done::SubUndone,
                            overdue: false,
                            index: 5,
                        },
                    ],
                    reset_on_done: Reset::No,
                    priority: 0,
                    done: Done::Undone,
                    overdue: true,
                    index: 1,
                },
                Task {
                    name: String::from("test2"),
                    description: None,
                    due: None,
                    tags: vec![],
                    subtasks: vec![],
                    reset_on_done: Reset::No,
                    priority: 0,
                    done: Done::Done,
                    overdue: true,
                    index: 6,
                },
            ],
            vec![],
        );

        todos.remove_nth_task(&vec![2, 7], true, false);

        assert_eq!(todos, correct);
    }

    #[test]
    fn done() {
        let mut todos = Profile::new(
            "test".to_string(),
            vec![
                Task {
                    name: String::from("test1"),
                    description: None,
                    due: None,
                    tags: vec![],
                    subtasks: vec![
                        Task {
                            name: String::from("test1"),
                            description: None,
                            due: None,
                            tags: vec![],
                            subtasks: vec![],
                            reset_on_done: Reset::NotRoot,
                            priority: 0,
                            done: Done::Undone,
                            overdue: true,
                            index: 2,
                        },
                        Task {
                            name: String::from("test2"),
                            description: None,
                            due: None,
                            tags: vec![],
                            subtasks: vec![],
                            reset_on_done: Reset::NotRoot,
                            priority: 0,
                            done: Done::Done,
                            overdue: true,
                            index: 3,
                        },
                        Task {
                            name: String::from("test3"),
                            description: None,
                            due: None,
                            tags: vec![],
                            subtasks: vec![],
                            reset_on_done: Reset::NotRoot,
                            priority: 1000,
                            done: Done::Done,
                            overdue: false,
                            index: 4,
                        },
                        Task {
                            name: String::from("test4"),
                            description: None,
                            due: None,
                            tags: vec![],
                            subtasks: vec![],
                            reset_on_done: Reset::NotRoot,
                            priority: 100,
                            done: Done::Done,
                            overdue: false,
                            index: 5,
                        },
                    ],
                    reset_on_done: Reset::Yes(vec![]),
                    priority: 0,
                    done: Done::SubUndone,
                    overdue: true,
                    index: 1,
                },
                Task {
                    name: String::from("test2"),
                    description: None,
                    due: None,
                    tags: vec![],
                    subtasks: vec![],
                    reset_on_done: Reset::No,
                    priority: 0,
                    done: Done::Done,
                    overdue: true,
                    index: 6,
                },
                Task {
                    name: String::from("test3"),
                    description: None,
                    due: None,
                    tags: vec![],
                    subtasks: vec![],
                    reset_on_done: Reset::No,
                    priority: 1000,
                    done: Done::Done,
                    overdue: false,
                    index: 7,
                },
                Task {
                    name: String::from("test4"),
                    description: None,
                    due: None,
                    tags: vec![],
                    subtasks: vec![],
                    reset_on_done: Reset::No,
                    priority: 100,
                    done: Done::Undone,
                    overdue: false,
                    index: 8,
                },
            ],
            vec![],
        );
        let correct = Profile::new(
            "test".to_string(),
            vec![
                Task {
                    name: String::from("test1"),
                    description: None,
                    due: None,
                    tags: vec![],
                    subtasks: vec![
                        Task {
                            name: String::from("test3"),
                            description: None,
                            due: None,
                            tags: vec![],
                            subtasks: vec![],
                            reset_on_done: Reset::NotRoot,
                            priority: 1000,
                            done: Done::Undone,
                            overdue: false,
                            index: 2,
                        },
                        Task {
                            name: String::from("test4"),
                            description: None,
                            due: None,
                            tags: vec![],
                            subtasks: vec![],
                            reset_on_done: Reset::NotRoot,
                            priority: 100,
                            done: Done::Undone,
                            overdue: false,
                            index: 3,
                        },
                        Task {
                            name: String::from("test1"),
                            description: None,
                            due: None,
                            tags: vec![],
                            subtasks: vec![],
                            reset_on_done: Reset::NotRoot,
                            priority: 0,
                            done: Done::Undone,
                            overdue: false,
                            index: 4,
                        },
                        Task {
                            name: String::from("test2"),
                            description: None,
                            due: None,
                            tags: vec![],
                            subtasks: vec![],
                            reset_on_done: Reset::NotRoot,
                            priority: 0,
                            done: Done::Undone,
                            overdue: false,
                            index: 5,
                        },
                    ],
                    reset_on_done: Reset::Yes(vec![]),
                    priority: 0,
                    done: Done::SubUndone,
                    overdue: false,
                    index: 1,
                },
                Task {
                    name: String::from("test3"),
                    description: None,
                    due: None,
                    tags: vec![],
                    subtasks: vec![],
                    reset_on_done: Reset::No,
                    priority: 1000,
                    done: Done::Done,
                    overdue: false,
                    index: 6,
                },
                Task {
                    name: String::from("test4"),
                    description: None,
                    due: None,
                    tags: vec![],
                    subtasks: vec![],
                    reset_on_done: Reset::No,
                    priority: 100,
                    done: Done::Done,
                    overdue: false,
                    index: 7,
                },
                Task {
                    name: String::from("test2"),
                    description: None,
                    due: None,
                    tags: vec![],
                    subtasks: vec![],
                    reset_on_done: Reset::No,
                    priority: 0,
                    done: Done::Done,
                    overdue: false,
                    index: 8,
                },
            ],
            vec![],
        );

        todos.done(2).unwrap();
        todos.tasks[1].reset_on_done = Reset::Yes(vec![]);
        todos.done(1).unwrap();
        assert_eq!(todos, correct);
    }
}
